Repository GoogleEyes-ewha/hearo-server, pull requests merged in 2024-02, with the labels that each got.

#5 [Feature] 일반 회원가입, 로그인 구현
  build.gradle
  src/main/java/com/gdsc/hearo/domain/item/entity/Wish.java
  src/main/java/com/gdsc/hearo/domain/member/controller/MemberController.java
  src/main/java/com/gdsc/hearo/domain/member/dto/LoginRequestDto.java
  src/main/java/com/gdsc/hearo/domain/member/dto/LoginResponseDto.java
  src/main/java/com/gdsc/hearo/domain/member/dto/SignupRequestDto.java
  src/main/java/com/gdsc/hearo/domain/member/entity/Member.java
  src/main/java/com/gdsc/hearo/domain/member/entity/MemberSetting.java
  src/main/java/com/gdsc/hearo/domain/member/repository/MemberRepository.java
  src/main/java/com/gdsc/hearo/domain/member/service/MemberService.java
  src/main/java/com/gdsc/hearo/global/common/BaseResponse.java
  src/main/java/com/gdsc/hearo/global/common/BaseResponseStatus.java
  src/main/java/com/gdsc/hearo/global/config/PasswordEncoderConfig.java
  src/main/java/com/gdsc/hearo/global/config/SecurityConfig.java
  src/main/java/com/gdsc/hearo/global/security/CustomUserDetails.java
  src/main/java/com/gdsc/hearo/global/security/JwtAuthFilter.java
  src/main/java/com/gdsc/hearo/global/security/JwtUtil.java
  src/main/resources/application.yml
Labels: ✨ Feature, 해원

#8 [Feature] 사용자 맞춤 설정 API 구현
  src/main/java/com/gdsc/hearo/domain/member/controller/MemberController.java
  src/main/java/com/gdsc/hearo/domain/member/dto/CustomEditResponseDto.java
  src/main/java/com/gdsc/hearo/domain/member/dto/CustomRequestDto.java
  src/main/java/com/gdsc/hearo/domain/member/dto/CustomResponseDto.java
  src/main/java/com/gdsc/hearo/domain/member/entity/Member.java
  src/main/java/com/gdsc/hearo/domain/member/entity/MemberSetting.java
  src/main/java/com/gdsc/hearo/domain/member/repository/MemberSettingRepository.java
  src/main/java/com/gdsc/hearo/domain/member/service/MemberSettingService.java
Labels: ✨ Feature, 해원

#12 [Feature] ItemTts, ReviewTts 엔티티 수정
  src/main/java/com/gdsc/hearo/domain/item/entity/ItemTts.java
  src/main/java/com/gdsc/hearo/domain/review/entity/ReviewTts.java
Labels: ✨ Feature, 해원

#15 [Feature] Review API 구현
  src/main/java/com/gdsc/hearo/domain/item/entity/ItemTts.java
  src/main/java/com/gdsc/hearo/domain/member/dto/CustomRequestDto.java
  src/main/java/com/gdsc/hearo/domain/member/dto/CustomResponseDto.java
  src/main/java/com/gdsc/hearo/domain/member/entity/MemberSetting.java
  src/main/java/com/gdsc/hearo/domain/review/controller/ReviewController.java
  src/main/java/com/gdsc/hearo/domain/review/dto/ReviewDto.java
  src/main/java/com/gdsc/hearo/domain/review/dto/ReviewListResponseDto.java
  src/main/java/com/gdsc/hearo/domain/review/dto/ReviewTTSDto.java
  src/main/java/com/gdsc/hearo/domain/review/entity/ReviewTts.java
  src/main/java/com/gdsc/hearo/domain/review/repository/ReviewRepository.java
  src/main/java/com/gdsc/hearo/domain/review/repository/ReviewTtsRepository.java
  src/main/java/com/gdsc/hearo/domain/review/service/ReviewService.java
  src/main/java/com/gdsc/hearo/global/common/BaseException.java
  src/main/java/com/gdsc/hearo/global/common/BaseResponse.java
  src/main/java/com/gdsc/hearo/global/common/BaseResponseStatus.java
  src/main/java/com/gdsc/hearo/global/common/VoiceType.java
Labels: ✨ Feature, 해원

#19 [Feature]찜 리스트 조회
  src/main/java/com/gdsc/hearo/domain/item/controller/WishController.java
  src/main/java/com/gdsc/hearo/domain/item/dto/WishListResponseDto.java
  src/main/java/com/gdsc/hearo/domain/item/repository/WishRepository.java
  src/main/java/com/gdsc/hearo/domain/item/service/WishService.java
Labels: ✨ Feature, 영서

#21 [Feature] 찜 상품 삭제 기능 구현
  src/main/java/com/gdsc/hearo/HearoApplication.java
  src/main/java/com/gdsc/hearo/domain/item/controller/WishController.java
  src/main/java/com/gdsc/hearo/domain/item/dto/WishRequestDto.java
  src/main/java/com/gdsc/hearo/domain/item/dto/WishResponseDto.java
  src/main/java/com/gdsc/hearo/domain/item/repository/WishRepository.java
  src/main/java/com/gdsc/hearo/domain/item/service/WishService.java
Labels: ✨ Feature, 영서

#24 [Feature] 액세스 토큰 재발급 API 구현
  src/main/java/com/gdsc/hearo/domain/member/controller/MemberController.java
  src/main/java/com/gdsc/hearo/domain/member/dto/ReissueRequestDto.java
  src/main/java/com/gdsc/hearo/domain/member/service/MemberService.java
  src/main/java/com/gdsc/hearo/global/common/BaseResponseStatus.java
  src/main/java/com/gdsc/hearo/global/security/JwtUtil.java
Labels: ✨ Feature, 해원

#27 [Feature] 사용자 정보 조회 API 구현
  src/main/java/com/gdsc/hearo/domain/member/controller/MemberController.java
  src/main/java/com/gdsc/hearo/domain/member/dto/UserInfoResponseDto.java
  src/main/java/com/gdsc/hearo/domain/member/service/MemberService.java
Labels: ✨ Feature, 해원

#28 [Feature] 리뷰 요약 API 구현
  src/main/java/com/gdsc/hearo/domain/review/config/GeminiRestTemplateConfig.java
  src/main/java/com/gdsc/hearo/domain/review/controller/ReviewController.java
  src/main/java/com/gdsc/hearo/domain/review/dto/ChatRequest.java
  src/main/java/com/gdsc/hearo/domain/review/dto/ChatResponse.java
  src/main/java/com/gdsc/hearo/domain/review/dto/SummaryResponseDto.java
  src/main/java/com/gdsc/hearo/domain/review/service/ReviewService.java
  src/main/java/com/gdsc/hearo/global/common/BaseResponseStatus.java
  src/main/resources/application.yml
Labels: ✨ Feature, 해원

#30 [Feature] 구글 소셜 로그인 API 구현
  src/main/java/com/gdsc/hearo/domain/oauth/controller/OauthController.java
  src/main/java/com/gdsc/hearo/domain/oauth/dto/GoogleOAuthToken.java
  src/main/java/com/gdsc/hearo/domain/oauth/dto/GoogleProfile.java
  src/main/java/com/gdsc/hearo/domain/oauth/service/OauthService.java
  src/main/java/com/gdsc/hearo/domain/oauth/service/social/GoogleOauth.java
  src/main/java/com/gdsc/hearo/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ Feature, 해원

#34 [Fix] 소셜로그인 저장 조건 수정
  src/main/java/com/gdsc/hearo/domain/oauth/service/OauthService.java
Labels: 해원, fix

#40 [Feature] 구글 소셜 로그인 redirect 추가
  src/main/java/com/gdsc/hearo/domain/oauth/controller/OauthController.java
  src/main/java/com/gdsc/hearo/domain/oauth/service/OauthService.java
Labels: ✨ Feature, 해원
